CREATE TABLE IF NOT EXISTS staff
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dep_code VARCHAR(20) NOT NULL,
	dep_job VARCHAR(100) NOT NULL,
	description VARCHAR(255),
	CONSTRAINT dep_code_job_unq UNIQUE(dep_code, dep_job)
);
INSERT INTO staff (dep_code, dep_job, description)
VALUES	('IT', 'Java developer', 'Backend developer'),
		('FIN', 'Economist', 'Major economist'),
		('ORG', 'Chef', 'Org department chef'),
		('IT', 'PHP developer', 'Backend php developer'
);
